version: '3.8'

services:
    example-frontend:
      image: example-frontend
      ports:
        - 5000:5000
      command: ["serve", "-s", "-l", "5000", "build"]
      container_name: frontend

    example-backend:
      image: example-backend
      ports:
        - 8080:8080
      environment:
        - REQUEST_ORIGIN=http://localhost
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      command: ./server
      container_name: backend

    proxy:
      image: nginx:latest
      volumes:
        - type: bind
          source: ./nginx.conf
          target: /etc/nginx/nginx.conf
      ports:
        - 80:80
      container_name: proxy

    redis:
      image: redis
      container_name: redis

    postgres:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: postgres
      volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data


